### PR TITLE
Replace API Rest endpoints with GraphQL

### PR DESCRIPTION
**Pull request by smorcuend**
vue-apollo added. Testing with some stats from github APIv4. 

Note: You can find `.env.{mode}.local` to set right github token 

Screenshot from 2019-10-09 19-03-29

### CODE REVIEW

**Comment by smorcuend** [comment]
#221

**Comment by smorcuend** [comment]
Referenced here: https://github.com/OSWeekends/osw-hacktoberfest-2019/issues/196

**Comment by baumannzone** [comment]
image

**Comment by smorcuend** [comment]
@baumannzone as told you above, you need to generate token for api_v4 authentication and store it as env. variable on devops workflow
https://developer.github.com/v4/guides/forming-calls/#authenticating-with-graphql

**Pull request closed without merging**
