### PR TITLE
Add contributors location came from

### PR DESCRIPTION
**Pull request by igihcksn**
Here i open new pull request for adding contributors location, i hope its better than before

### CODE REVIEW

**Comment by igihcksn** [comment]
here i try to fix [issue](https://github.com/OSWeekends/osw-hacktoberfest-2019/issues/59)

**Comment by baumannzone** [comment]
> here i try to fix [issue](https://github.com/OSWeekends/osw-hacktoberfest-2019/issues/59)

I think I may accept your request, but you should not merge multiple tasks (issues) in one request.

Think, maybe I like one feature but I don't like the second. I couldn't accept it because of the second one.

**Comment by baumannzone** [comment]
@all-contributors please add @igihcksn for code

**Comment by igihcksn** [comment]
Sory for many mistake i have, from here i learn many point of open source project

Thanks for your help, and nice to know you   :smile:

**Comment by baumannzone** [comment]
Don't worry. Feel free to improve anything you want via PR or request for a feature in the issues.

**Pull request merged**
